export type Sport = 'badminton' | 'football' | 'motogp' | 'running' | 'cycling' | 'surfing' | 'basketball' | 'volleyball' | 'swimming' | 'athletics' | 'tennis' | 'golf' | 'esports' | 'martial-arts' | 'multi-sport' | 'motorsport';

export interface SportEvent {
  id: string;
  slug: string;
  title: string;
  sport: Sport;
  category: 'international' | 'national' | 'regional';
  status: 'confirmed' | 'tentative' | 'completed';
  startDate: string;
  endDate: string;
  venue: string;
  city: string;
  country: string;
  description: string;
  ticketUrl?: string;
  websiteUrl?: string;
  priceRange?: string;
  imageEmoji: string;
  tags: string[];
  athletes?: string;
  organizer?: string;
  highlights?: string[];
}

export const SPORT_EMOJI: Record<Sport, string> = {
  badminton: '🏸',
  football: '⚽',
  motogp: '🏍️',
  running: '🏃',
  cycling: '🚴',
  surfing: '🏄',
  basketball: '🏀',
  volleyball: '🏐',
  swimming: '🏊',
  athletics: '🏃',
  tennis: '🎾',
  golf: '⛳',
  esports: '🎮',
  'martial-arts': '🥋',
  'multi-sport': '🏆',
  motorsport: '🏎️',
};

export const SPORT_LABELS: Record<Sport, string> = {
  badminton: 'Bulu Tangkis',
  football: 'Sepak Bola',
  motogp: 'MotoGP',
  running: 'Lari',
  cycling: 'Balap Sepeda',
  surfing: 'Selancar',
  basketball: 'Basket',
  volleyball: 'Voli',
  swimming: 'Renang',
  athletics: 'Atletik',
  tennis: 'Tenis',
  golf: 'Golf',
  esports: 'Esports',
  'martial-arts': 'Beladiri',
  'multi-sport': 'Multi Olahraga',
  motorsport: 'Motorsport',
};

export const events: SportEvent[] = [
  {
    id: '1',
    slug: 'indonesia-masters-2026',
    title: 'Indonesia Masters 2026',
    sport: 'badminton',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-01-20',
    endDate: '2026-01-25',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Turnamen bulu tangkis kelas Super 500 yang menjadi pembuka musim BWF World Tour. Atlet terbaik dunia berkompetisi di Istora Senayan.',
    ticketUrl: 'https://tiket.com',
    websiteUrl: 'https://bwfworldtour.bwfbadminton.com',
    priceRange: 'Rp 150.000 - Rp 1.500.000',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 500', 'World Tour'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
    highlights: [
      'Turnamen pembuka musim BWF World Tour 2026',
      'Kategori Super 500 dengan poin ranking dunia penuh',
      'Digelar di Istora Senayan, arena bulu tangkis paling ikonik di Indonesia',
      'Tim Indonesia ditargetkan raih minimal 2 gelar juara',
    ],
  },
  {
    id: '2',
    slug: 'liga-1-2026',
    title: 'Liga 1 Indonesia 2026',
    sport: 'football',
    category: 'national',
    status: 'confirmed',
    startDate: '2026-02-01',
    endDate: '2026-12-15',
    venue: 'Berbagai Stadion',
    city: 'Seluruh Indonesia',
    country: 'Indonesia',
    description: 'Kompetisi liga sepak bola tertinggi Indonesia musim 2026. 18 klub terbaik bertarung memperebutkan gelar juara.',
    websiteUrl: 'https://liga-indonesia.id',
    priceRange: 'Rp 50.000 - Rp 500.000',
    imageEmoji: '⚽',
    tags: ['Liga 1', 'Sepak Bola', 'Domestik'],
    organizer: 'PT LIB',
  },
  {
    id: '3',
    slug: 'jakarta-marathon-2026',
    title: 'Jakarta Marathon 2026',
    sport: 'running',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-10-25',
    endDate: '2026-10-25',
    venue: 'Monas - Jakarta',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Marathon internasional tahunan di ibu kota Indonesia. Rute melewati landmark ikonik Jakarta dengan kategori Full Marathon, Half Marathon, dan 10K.',
    ticketUrl: 'https://jakartamarathon.com',
    websiteUrl: 'https://jakartamarathon.com',
    priceRange: 'Rp 350.000 - Rp 1.200.000',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Running', 'Jakarta'],
    organizer: 'Jakarta Marathon Foundation',
    highlights: [
      'Rute melewati Monas, Bundaran HI, dan Kota Tua Jakarta',
      '3 kategori: Full Marathon (42km), Half Marathon (21km), dan 10K',
      'Lebih dari 10.000 pelari dari 50+ negara',
      'Finisher medal eksklusif dan goody bag resmi',
    ],
  },
  {
    id: '4',
    slug: 'indonesia-open-2026',
    title: 'Indonesia Open 2026',
    sport: 'badminton',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-06-09',
    endDate: '2026-06-14',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Turnamen bulu tangkis paling bergengsi di Indonesia, bagian dari BWF World Tour Super 1000. Hadiah total jutaan dolar AS.',
    ticketUrl: 'https://tiket.com',
    websiteUrl: 'https://bwfworldtour.bwfbadminton.com',
    priceRange: 'Rp 200.000 - Rp 2.500.000',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 1000', 'World Tour'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
    highlights: [
      'Turnamen BWF Super 1000 — level tertinggi di World Tour',
      'Total hadiah jutaan dolar AS untuk para pemenang',
      'Kevin/Marcus dan Fajar/Rian jadi andalan ganda putra Indonesia',
      'Tiket final selalu sold out dalam hitungan jam',
    ],
  },
  {
    id: '5',
    slug: 'asian-games-2026',
    title: 'Asian Games 2026 - Kontingen Indonesia',
    sport: 'multi-sport',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-09-19',
    endDate: '2026-10-04',
    venue: 'Aichi-Nagoya',
    city: 'Nagoya',
    country: 'Jepang',
    description: 'Pesta olahraga terbesar Asia. Kontingen Indonesia mengirim ratusan atlet terbaik untuk bertarung meraih medali emas di berbagai cabang olahraga.',
    websiteUrl: 'https://aichi-nagoya2026.org',
    imageEmoji: '🏆',
    tags: ['Asian Games', 'Multi Sport', 'Jepang'],
    athletes: 'Tim Indonesia',
    organizer: 'OCA',
    highlights: [
      '45 cabang olahraga diperebutkan selama 16 hari',
      'Indonesia targetkan masuk 5 besar perolehan medali',
      'Bulu tangkis, angkat besi, dan pencak silat jadi andalan emas',
      'Digelar di Aichi-Nagoya, Jepang',
    ],
  },
  {
    id: '6',
    slug: 'motogp-mandalika-2026',
    title: 'MotoGP Indonesian Grand Prix 2026',
    sport: 'motogp',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-10-09',
    endDate: '2026-10-11',
    venue: 'Mandalika International Street Circuit',
    city: 'Lombok',
    country: 'Indonesia',
    description: 'Balapan MotoGP di sirkuit Mandalika, Lombok. Sirkuit internasional dengan pemandangan pantai yang memukau.',
    ticketUrl: 'https://tiket.com',
    websiteUrl: 'https://www.motogp.com',
    priceRange: 'Rp 500.000 - Rp 15.000.000',
    imageEmoji: '🏍️',
    tags: ['MotoGP', 'Mandalika', 'Lombok'],
    organizer: 'Dorna Sports / MGPA',
    highlights: [
      'Satu-satunya sirkuit MotoGP di Indonesia dengan pemandangan pantai',
      '3 hari penuh hiburan: FP, Qualifying, Sprint Race, dan Main Race',
      'Kapasitas 150.000 penonton per hari di tribun dan hillstand',
      'Rider top dunia: Marquez, Bagnaia, Martin, dan Quartararo',
    ],
  },
  {
    id: '7',
    slug: 'fifa-world-cup-2026-indonesia',
    title: 'FIFA World Cup 2026 - Tim Indonesia',
    sport: 'football',
    category: 'international',
    status: 'tentative',
    startDate: '2026-06-11',
    endDate: '2026-07-19',
    venue: 'USA, Meksiko, Kanada',
    city: 'Berbagai Kota',
    country: 'USA/Meksiko/Kanada',
    description: 'Piala Dunia FIFA 2026, turnamen sepak bola terbesar di dunia. Indonesia berpeluang tampil untuk pertama kalinya dalam sejarah.',
    websiteUrl: 'https://www.fifa.com/fifaplus/en/tournaments/mens/worldcup/canadamexicousa2026',
    imageEmoji: '⚽',
    tags: ['FIFA', 'World Cup', 'Piala Dunia'],
    athletes: 'Timnas Indonesia',
    organizer: 'FIFA',
    highlights: [
      'Pertama kalinya Indonesia berpotensi tampil di Piala Dunia FIFA',
      'Format baru: 48 tim dari seluruh dunia berpartisipasi',
      'Digelar di 3 negara: USA, Meksiko, dan Kanada',
      'Shin Tae-yong memimpin skuad Garuda menuju panggung dunia',
    ],
  },
  {
    id: '8',
    slug: 'bali-marathon-2026',
    title: 'Bali Marathon 2026',
    sport: 'running',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-05-17',
    endDate: '2026-05-17',
    venue: 'Gianyar - Bali',
    city: 'Gianyar',
    country: 'Indonesia',
    description: 'Marathon bertaraf internasional di Pulau Dewata. Rute melewati sawah, pura, dan pemandangan alam Bali yang indah.',
    ticketUrl: 'https://balimarathon.com',
    websiteUrl: 'https://balimarathon.com',
    priceRange: 'Rp 500.000 - Rp 1.500.000',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Bali', 'Running'],
    organizer: 'Bali Marathon Org.',
  },
  {
    id: '9',
    slug: 'borobudur-marathon-2026',
    title: 'Borobudur Marathon 2026',
    sport: 'running',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-11-15',
    endDate: '2026-11-15',
    venue: 'Candi Borobudur',
    city: 'Magelang',
    country: 'Indonesia',
    description: 'Lari marathon dengan pemandangan Candi Borobudur sebagai latar belakang. Salah satu marathon paling indah di Asia.',
    ticketUrl: 'https://borobudurmarathon.com',
    websiteUrl: 'https://borobudurmarathon.com',
    priceRange: 'Rp 400.000 - Rp 1.200.000',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Borobudur', 'Heritage'],
    organizer: 'Bank Jateng',
  },
  {
    id: '10',
    slug: 'tour-de-banyuwangi-2026',
    title: 'Tour de Banyuwangi Ijen 2026',
    sport: 'cycling',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-09-20',
    endDate: '2026-09-24',
    venue: 'Banyuwangi',
    city: 'Banyuwangi',
    country: 'Indonesia',
    description: 'Balap sepeda internasional di Banyuwangi dengan rute melewati pemandangan Gunung Ijen dan pantai timur Jawa.',
    websiteUrl: 'https://tourdebanyuwangi.com',
    imageEmoji: '🚴',
    tags: ['Cycling', 'UCI', 'Banyuwangi'],
    organizer: 'Pemkab Banyuwangi',
  },
  {
    id: '11',
    slug: 'indonesia-surfing-championship-2026',
    title: 'Indonesia Surfing Championship 2026',
    sport: 'surfing',
    category: 'national',
    status: 'confirmed',
    startDate: '2026-07-10',
    endDate: '2026-07-15',
    venue: 'G-Land',
    city: 'Banyuwangi',
    country: 'Indonesia',
    description: 'Kompetisi selancar nasional di G-Land, salah satu spot surfing terbaik dunia di pantai selatan Jawa Timur.',
    imageEmoji: '🏄',
    tags: ['Surfing', 'G-Land', 'ISC'],
    organizer: 'ISA / PSOI',
  },
  {
    id: '12',
    slug: 'indonesia-open-tennis-2026',
    title: 'Indonesia Open Tennis 2026',
    sport: 'tennis',
    category: 'international',
    status: 'tentative',
    startDate: '2026-07-27',
    endDate: '2026-08-02',
    venue: 'Senayan Tennis Courts',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Turnamen tenis internasional yang diselenggarakan di Jakarta, bagian dari kalender ATP/WTA.',
    imageEmoji: '🎾',
    tags: ['Tennis', 'ATP', 'Jakarta'],
    organizer: 'Pelti',
  },
  {
    id: '13',
    slug: 'indonesia-open-golf-2026',
    title: 'Indonesia Open Golf 2026',
    sport: 'golf',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-08-06',
    endDate: '2026-08-09',
    venue: 'Damai Indah Golf',
    city: 'Tangerang',
    country: 'Indonesia',
    description: 'Turnamen golf internasional tertua di Asia Tenggara, bagian dari Asian Tour.',
    websiteUrl: 'https://indonesiaopengolf.com',
    priceRange: 'Rp 100.000 - Rp 500.000',
    imageEmoji: '⛳',
    tags: ['Golf', 'Asian Tour', 'Jakarta'],
    organizer: 'PGI',
  },
  {
    id: '14',
    slug: 'wsbk-mandalika-2026',
    title: 'WSBK Mandalika 2026',
    sport: 'motorsport',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-11-13',
    endDate: '2026-11-15',
    venue: 'Mandalika International Street Circuit',
    city: 'Lombok',
    country: 'Indonesia',
    description: 'World Superbike Championship di Sirkuit Mandalika. Balap motor sport produksi tercepat di dunia.',
    ticketUrl: 'https://tiket.com',
    priceRange: 'Rp 250.000 - Rp 5.000.000',
    imageEmoji: '🏎️',
    tags: ['WSBK', 'Mandalika', 'Superbike'],
    organizer: 'Dorna / MGPA',
  },
  {
    id: '15',
    slug: 'jakarta-international-10k-2026',
    title: 'Jakarta International 10K 2026',
    sport: 'running',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-04-12',
    endDate: '2026-04-12',
    venue: 'Gelora Bung Karno',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Lomba lari 10K internasional di jantung kota Jakarta. Event yang cocok untuk pelari pemula hingga profesional.',
    priceRange: 'Rp 200.000 - Rp 500.000',
    imageEmoji: '🏃',
    tags: ['10K', 'Running', 'Jakarta'],
    organizer: 'Jakarta Running',
  },
  {
    id: '16',
    slug: 'tour-de-flores-2026',
    title: 'Tour de Flores 2026',
    sport: 'cycling',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-05-05',
    endDate: '2026-05-10',
    venue: 'Flores, NTT',
    city: 'Flores',
    country: 'Indonesia',
    description: 'Balap sepeda multi-etape di Pulau Flores dengan pemandangan alam NTT yang menakjubkan.',
    imageEmoji: '🚴',
    tags: ['Cycling', 'Flores', 'NTT'],
    organizer: 'Pemprov NTT',
  },
  {
    id: '17',
    slug: 'sea-games-2027',
    title: 'SEA Games 2027 - Kontingen Indonesia',
    sport: 'multi-sport',
    category: 'international',
    status: 'confirmed',
    startDate: '2027-05-15',
    endDate: '2027-05-26',
    venue: 'Kuala Lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    description: 'Pesta olahraga terbesar Asia Tenggara. Indonesia mengirim kontingen terbaik untuk bersaing meraih juara umum.',
    websiteUrl: 'https://seagames2027.com',
    imageEmoji: '🏆',
    tags: ['SEA Games', 'Multi Sport', 'Malaysia'],
    athletes: 'Tim Indonesia',
    organizer: 'SEAGF',
  },
  {
    id: '18',
    slug: 'motogp-mandalika-2027',
    title: 'MotoGP Indonesian Grand Prix 2027',
    sport: 'motogp',
    category: 'international',
    status: 'tentative',
    startDate: '2027-10-10',
    endDate: '2027-10-12',
    venue: 'Mandalika International Street Circuit',
    city: 'Lombok',
    country: 'Indonesia',
    description: 'Seri MotoGP di Mandalika untuk musim 2027. Sirkuit pantai favorit para pembalap.',
    priceRange: 'Rp 500.000 - Rp 15.000.000',
    imageEmoji: '🏍️',
    tags: ['MotoGP', 'Mandalika', '2027'],
    organizer: 'Dorna Sports / MGPA',
  },
  {
    id: '19',
    slug: 'indonesia-masters-2027',
    title: 'Indonesia Masters 2027',
    sport: 'badminton',
    category: 'international',
    status: 'tentative',
    startDate: '2027-01-21',
    endDate: '2027-01-26',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'BWF World Tour Super 500 pembuka musim 2027 di Jakarta.',
    priceRange: 'Rp 150.000 - Rp 1.500.000',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 500', '2027'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
  },
  {
    id: '20',
    slug: 'indonesia-open-2027',
    title: 'Indonesia Open 2027',
    sport: 'badminton',
    category: 'international',
    status: 'tentative',
    startDate: '2027-06-10',
    endDate: '2027-06-15',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'BWF World Tour Super 1000 di Indonesia untuk tahun 2027.',
    priceRange: 'Rp 200.000 - Rp 2.500.000',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 1000', '2027'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
  },
  {
    id: '21',
    slug: 'jakarta-marathon-2027',
    title: 'Jakarta Marathon 2027',
    sport: 'running',
    category: 'international',
    status: 'tentative',
    startDate: '2027-10-24',
    endDate: '2027-10-24',
    venue: 'Monas - Jakarta',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Edisi tahunan Jakarta Marathon 2027 dengan rute baru.',
    priceRange: 'Rp 350.000 - Rp 1.200.000',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Jakarta', '2027'],
    organizer: 'Jakarta Marathon Foundation',
  },
  {
    id: '22',
    slug: 'liga-1-2027',
    title: 'Liga 1 Indonesia 2027',
    sport: 'football',
    category: 'national',
    status: 'tentative',
    startDate: '2027-02-01',
    endDate: '2027-12-15',
    venue: 'Berbagai Stadion',
    city: 'Seluruh Indonesia',
    country: 'Indonesia',
    description: 'Kompetisi liga sepak bola tertinggi Indonesia musim 2027.',
    priceRange: 'Rp 50.000 - Rp 500.000',
    imageEmoji: '⚽',
    tags: ['Liga 1', 'Sepak Bola', '2027'],
    organizer: 'PT LIB',
  },
  {
    id: '23',
    slug: 'olympics-2028-indonesia',
    title: 'Olimpiade Los Angeles 2028 - Tim Indonesia',
    sport: 'multi-sport',
    category: 'international',
    status: 'confirmed',
    startDate: '2028-07-14',
    endDate: '2028-07-30',
    venue: 'Los Angeles',
    city: 'Los Angeles',
    country: 'USA',
    description: 'Olimpiade musim panas 2028 di Los Angeles. Tim Indonesia menargetkan medali emas di bulu tangkis, angkat besi, dan panahan.',
    websiteUrl: 'https://la2028.org',
    imageEmoji: '🏆',
    tags: ['Olimpiade', 'LA 2028', 'Multi Sport'],
    athletes: 'Tim Indonesia',
    organizer: 'IOC',
  },
  {
    id: '24',
    slug: 'motogp-mandalika-2028',
    title: 'MotoGP Indonesian Grand Prix 2028',
    sport: 'motogp',
    category: 'international',
    status: 'tentative',
    startDate: '2028-10-08',
    endDate: '2028-10-10',
    venue: 'Mandalika International Street Circuit',
    city: 'Lombok',
    country: 'Indonesia',
    description: 'Seri MotoGP di Mandalika musim 2028.',
    priceRange: 'Rp 500.000 - Rp 15.000.000',
    imageEmoji: '🏍️',
    tags: ['MotoGP', 'Mandalika', '2028'],
    organizer: 'Dorna Sports / MGPA',
  },
  {
    id: '25',
    slug: 'pon-2028',
    title: 'PON XXI 2028',
    sport: 'multi-sport',
    category: 'national',
    status: 'tentative',
    startDate: '2028-09-10',
    endDate: '2028-09-20',
    venue: 'TBD',
    city: 'TBD',
    country: 'Indonesia',
    description: 'Pekan Olahraga Nasional (PON) ke-21, pesta olahraga terbesar tingkat nasional Indonesia. Seluruh provinsi mengirim atlet terbaik.',
    imageEmoji: '🏆',
    tags: ['PON', 'Nasional', 'Multi Sport'],
    organizer: 'KONI',
  },
  {
    id: '26',
    slug: 'sea-games-2029',
    title: 'SEA Games 2029 - Kontingen Indonesia',
    sport: 'multi-sport',
    category: 'international',
    status: 'tentative',
    startDate: '2029-05-10',
    endDate: '2029-05-21',
    venue: 'TBD',
    city: 'TBD',
    country: 'TBD',
    description: 'SEA Games 2029, tuan rumah belum ditentukan. Indonesia menargetkan juara umum.',
    imageEmoji: '🏆',
    tags: ['SEA Games', 'Multi Sport', '2029'],
    athletes: 'Tim Indonesia',
    organizer: 'SEAGF',
  },
  {
    id: '27',
    slug: 'asian-games-2030',
    title: 'Asian Games 2030',
    sport: 'multi-sport',
    category: 'international',
    status: 'tentative',
    startDate: '2030-09-20',
    endDate: '2030-10-05',
    venue: 'TBD',
    city: 'TBD',
    country: 'TBD',
    description: 'Asian Games 2030, tuan rumah belum ditentukan. Pesta olahraga Asia empat tahunan.',
    imageEmoji: '🏆',
    tags: ['Asian Games', 'Multi Sport', '2030'],
    athletes: 'Tim Indonesia',
    organizer: 'OCA',
  },
  {
    id: '28',
    slug: 'bali-marathon-2027',
    title: 'Bali Marathon 2027',
    sport: 'running',
    category: 'international',
    status: 'tentative',
    startDate: '2027-05-18',
    endDate: '2027-05-18',
    venue: 'Gianyar - Bali',
    city: 'Gianyar',
    country: 'Indonesia',
    description: 'Edisi tahunan Bali Marathon di tengah pemandangan sawah dan budaya Bali.',
    priceRange: 'Rp 500.000 - Rp 1.500.000',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Bali', '2027'],
    organizer: 'Bali Marathon Org.',
  },
  {
    id: '29',
    slug: 'indonesia-open-golf-2027',
    title: 'Indonesia Open Golf 2027',
    sport: 'golf',
    category: 'international',
    status: 'tentative',
    startDate: '2027-08-07',
    endDate: '2027-08-10',
    venue: 'Damai Indah Golf',
    city: 'Tangerang',
    country: 'Indonesia',
    description: 'Turnamen golf internasional tertua di Asia Tenggara, edisi 2027.',
    priceRange: 'Rp 100.000 - Rp 500.000',
    imageEmoji: '⛳',
    tags: ['Golf', 'Asian Tour', '2027'],
    organizer: 'PGI',
  },
  {
    id: '30',
    slug: 'indonesian-surfing-championship-bali-2026',
    title: 'Indonesian Surfing Championship Bali 2026',
    sport: 'surfing',
    category: 'national',
    status: 'confirmed',
    startDate: '2026-08-01',
    endDate: '2026-08-05',
    venue: 'Pantai Kuta & Uluwatu',
    city: 'Bali',
    country: 'Indonesia',
    description: 'Kejuaraan selancar nasional di pantai-pantai legendaris Bali. Seri kedua setelah G-Land.',
    imageEmoji: '🏄',
    tags: ['Surfing', 'Bali', 'Nasional'],
    organizer: 'PSOI',
  },
  {
    id: '31',
    slug: 'proliga-2026',
    title: 'Proliga Voli 2026',
    sport: 'volleyball',
    category: 'national',
    status: 'confirmed',
    startDate: '2026-01-10',
    endDate: '2026-04-20',
    venue: 'Berbagai Kota',
    city: 'Seluruh Indonesia',
    country: 'Indonesia',
    description: 'Liga voli profesional Indonesia. Pertandingan seru antara klub-klub terbaik putra dan putri.',
    priceRange: 'Rp 30.000 - Rp 200.000',
    imageEmoji: '🏐',
    tags: ['Voli', 'Proliga', 'Nasional'],
    organizer: 'PBVSI',
  },
  {
    id: '32',
    slug: 'ibl-2026',
    title: 'IBL (Indonesian Basketball League) 2026',
    sport: 'basketball',
    category: 'national',
    status: 'confirmed',
    startDate: '2026-01-15',
    endDate: '2026-06-30',
    venue: 'Berbagai Arena',
    city: 'Seluruh Indonesia',
    country: 'Indonesia',
    description: 'Liga basket profesional Indonesia dengan format reguler season dan playoff.',
    priceRange: 'Rp 50.000 - Rp 300.000',
    imageEmoji: '🏀',
    tags: ['Basket', 'IBL', 'Liga'],
    organizer: 'IBL',
  },
  {
    id: '33',
    slug: 'asian-para-games-2026',
    title: 'Asian Para Games 2026 - Tim Indonesia',
    sport: 'multi-sport',
    category: 'international',
    status: 'confirmed',
    startDate: '2026-10-17',
    endDate: '2026-10-23',
    venue: 'Aichi-Nagoya',
    city: 'Nagoya',
    country: 'Jepang',
    description: 'Pesta olahraga untuk atlet difabel terbesar Asia. Indonesia mengirim kontingen paralimpian terbaik.',
    imageEmoji: '🏆',
    tags: ['Para Games', 'Difabel', 'Asia'],
    athletes: 'Tim Indonesia Paralimpik',
    organizer: 'APC',
  },
  {
    id: '34',
    slug: 'pencak-silat-world-championship-2026',
    title: 'Pencak Silat World Championship 2026',
    sport: 'martial-arts',
    category: 'international',
    status: 'tentative',
    startDate: '2026-11-20',
    endDate: '2026-11-25',
    venue: 'TBD',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Kejuaraan dunia pencak silat. Indonesia sebagai negara asal olahraga ini menargetkan dominasi medali emas.',
    imageEmoji: '🥋',
    tags: ['Pencak Silat', 'Beladiri', 'Dunia'],
    athletes: 'Tim Indonesia',
    organizer: 'PERSILAT',
  },
  {
    id: '35',
    slug: 'esports-sea-games-qualifier-2026',
    title: 'SEA Games Esports Qualifier 2026',
    sport: 'esports',
    category: 'national',
    status: 'confirmed',
    startDate: '2026-03-15',
    endDate: '2026-03-20',
    venue: 'ICE BSD',
    city: 'Tangerang',
    country: 'Indonesia',
    description: 'Kualifikasi nasional esports untuk SEA Games. Game: Mobile Legends, PUBG Mobile, Valorant.',
    imageEmoji: '🎮',
    tags: ['Esports', 'SEA Games', 'MLBB'],
    organizer: 'PBESI',
  },
  {
    id: '36',
    slug: 'jakarta-marathon-2028',
    title: 'Jakarta Marathon 2028',
    sport: 'running',
    category: 'international',
    status: 'tentative',
    startDate: '2028-10-27',
    endDate: '2028-10-27',
    venue: 'Monas - Jakarta',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Edisi tahunan Jakarta Marathon 2028.',
    priceRange: 'Rp 400.000 - Rp 1.500.000',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Jakarta', '2028'],
    organizer: 'Jakarta Marathon Foundation',
  },
  {
    id: '37',
    slug: 'liga-1-2028',
    title: 'Liga 1 Indonesia 2028',
    sport: 'football',
    category: 'national',
    status: 'tentative',
    startDate: '2028-02-01',
    endDate: '2028-12-15',
    venue: 'Berbagai Stadion',
    city: 'Seluruh Indonesia',
    country: 'Indonesia',
    description: 'Liga sepak bola tertinggi Indonesia musim 2028.',
    priceRange: 'Rp 50.000 - Rp 500.000',
    imageEmoji: '⚽',
    tags: ['Liga 1', 'Sepak Bola', '2028'],
    organizer: 'PT LIB',
  },
  {
    id: '38',
    slug: 'indonesia-masters-2028',
    title: 'Indonesia Masters 2028',
    sport: 'badminton',
    category: 'international',
    status: 'tentative',
    startDate: '2028-01-18',
    endDate: '2028-01-23',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'BWF World Tour Super 500 pembuka musim 2028.',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 500', '2028'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
  },
  {
    id: '39',
    slug: 'indonesia-open-2028',
    title: 'Indonesia Open 2028',
    sport: 'badminton',
    category: 'international',
    status: 'tentative',
    startDate: '2028-06-11',
    endDate: '2028-06-16',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'BWF World Tour Super 1000 di Indonesia untuk tahun 2028.',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 1000', '2028'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
  },
  {
    id: '40',
    slug: 'borobudur-marathon-2027',
    title: 'Borobudur Marathon 2027',
    sport: 'running',
    category: 'international',
    status: 'tentative',
    startDate: '2027-11-14',
    endDate: '2027-11-14',
    venue: 'Candi Borobudur',
    city: 'Magelang',
    country: 'Indonesia',
    description: 'Edisi 2027 marathon ikonik dengan pemandangan Candi Borobudur.',
    priceRange: 'Rp 400.000 - Rp 1.200.000',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Borobudur', '2027'],
    organizer: 'Bank Jateng',
  },
  {
    id: '41',
    slug: 'liga-1-2029',
    title: 'Liga 1 Indonesia 2029',
    sport: 'football',
    category: 'national',
    status: 'tentative',
    startDate: '2029-02-01',
    endDate: '2029-12-15',
    venue: 'Berbagai Stadion',
    city: 'Seluruh Indonesia',
    country: 'Indonesia',
    description: 'Liga sepak bola tertinggi Indonesia musim 2029.',
    imageEmoji: '⚽',
    tags: ['Liga 1', 'Sepak Bola', '2029'],
    organizer: 'PT LIB',
  },
  {
    id: '42',
    slug: 'liga-1-2030',
    title: 'Liga 1 Indonesia 2030',
    sport: 'football',
    category: 'national',
    status: 'tentative',
    startDate: '2030-02-01',
    endDate: '2030-12-15',
    venue: 'Berbagai Stadion',
    city: 'Seluruh Indonesia',
    country: 'Indonesia',
    description: 'Liga sepak bola tertinggi Indonesia musim 2030.',
    imageEmoji: '⚽',
    tags: ['Liga 1', 'Sepak Bola', '2030'],
    organizer: 'PT LIB',
  },
  {
    id: '43',
    slug: 'jakarta-marathon-2029',
    title: 'Jakarta Marathon 2029',
    sport: 'running',
    category: 'international',
    status: 'tentative',
    startDate: '2029-10-28',
    endDate: '2029-10-28',
    venue: 'Monas - Jakarta',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Edisi tahunan Jakarta Marathon 2029.',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Jakarta', '2029'],
    organizer: 'Jakarta Marathon Foundation',
  },
  {
    id: '44',
    slug: 'indonesia-aquatic-championship-2027',
    title: 'Indonesia Aquatic Championship 2027',
    sport: 'swimming',
    category: 'national',
    status: 'tentative',
    startDate: '2027-04-10',
    endDate: '2027-04-14',
    venue: 'Aquatic Stadium GBK',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Kejuaraan renang nasional terbesar Indonesia. Ajang seleksi untuk multi-event internasional.',
    imageEmoji: '🏊',
    tags: ['Renang', 'Aquatik', 'Nasional'],
    organizer: 'PRSI',
  },
  {
    id: '45',
    slug: 'wsbk-mandalika-2027',
    title: 'WSBK Mandalika 2027',
    sport: 'motorsport',
    category: 'international',
    status: 'tentative',
    startDate: '2027-11-12',
    endDate: '2027-11-14',
    venue: 'Mandalika International Street Circuit',
    city: 'Lombok',
    country: 'Indonesia',
    description: 'World Superbike Championship di Sirkuit Mandalika tahun 2027.',
    priceRange: 'Rp 250.000 - Rp 5.000.000',
    imageEmoji: '🏎️',
    tags: ['WSBK', 'Mandalika', '2027'],
    organizer: 'Dorna / MGPA',
  },
  {
    id: '46',
    slug: 'indonesia-masters-2029',
    title: 'Indonesia Masters 2029',
    sport: 'badminton',
    category: 'international',
    status: 'tentative',
    startDate: '2029-01-22',
    endDate: '2029-01-27',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'BWF World Tour Super 500 pembuka musim 2029.',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 500', '2029'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
  },
  {
    id: '47',
    slug: 'indonesia-open-2029',
    title: 'Indonesia Open 2029',
    sport: 'badminton',
    category: 'international',
    status: 'tentative',
    startDate: '2029-06-12',
    endDate: '2029-06-17',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'BWF World Tour Super 1000 di Indonesia untuk tahun 2029.',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 1000', '2029'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
  },
  {
    id: '48',
    slug: 'jakarta-marathon-2030',
    title: 'Jakarta Marathon 2030',
    sport: 'running',
    category: 'international',
    status: 'tentative',
    startDate: '2030-10-27',
    endDate: '2030-10-27',
    venue: 'Monas - Jakarta',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'Edisi tahunan Jakarta Marathon 2030.',
    imageEmoji: '🏃',
    tags: ['Marathon', 'Jakarta', '2030'],
    organizer: 'Jakarta Marathon Foundation',
  },
  {
    id: '49',
    slug: 'indonesia-masters-2030',
    title: 'Indonesia Masters 2030',
    sport: 'badminton',
    category: 'international',
    status: 'tentative',
    startDate: '2030-01-21',
    endDate: '2030-01-26',
    venue: 'Istora Senayan',
    city: 'Jakarta',
    country: 'Indonesia',
    description: 'BWF World Tour Super 500 pembuka musim 2030.',
    imageEmoji: '🏸',
    tags: ['BWF', 'Super 500', '2030'],
    athletes: 'Tim Indonesia',
    organizer: 'PBSI',
  },
  {
    id: '50',
    slug: 'motogp-mandalika-2029',
    title: 'MotoGP Indonesian Grand Prix 2029',
    sport: 'motogp',
    category: 'international',
    status: 'tentative',
    startDate: '2029-10-12',
    endDate: '2029-10-14',
    venue: 'Mandalika International Street Circuit',
    city: 'Lombok',
    country: 'Indonesia',
    description: 'Seri MotoGP di Mandalika musim 2029.',
    priceRange: 'Rp 500.000 - Rp 15.000.000',
    imageEmoji: '🏍️',
    tags: ['MotoGP', 'Mandalika', '2029'],
    organizer: 'Dorna Sports / MGPA',
  },
];

export function getEventBySlug(slug: string): SportEvent | undefined {
  return events.find((e) => e.slug === slug);
}

export function getUpcomingEvents(): SportEvent[] {
  const now = new Date().toISOString().split('T')[0];
  return events.filter((e) => e.startDate >= now).sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getAllCities(): string[] {
  return [...new Set(events.map((e) => e.city))].sort();
}

export function getAllYears(): number[] {
  return [...new Set(events.map((e) => new Date(e.startDate).getFullYear()))].sort();
}

export function getAllSports(): Sport[] {
  return [...new Set(events.map((e) => e.sport))].sort();
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('id-ID', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

export function formatDateShort(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('id-ID', {
    day: 'numeric',
    month: 'short',
  });
}
