import { SPORT_LABELS, type SportEvent } from './data';

export const SITE_URL = 'https://www.sport-event.web.id';

// Generated by src/app/opengraph-image.tsx — the repo ships no static images,
// so this is the only crawlable image URL available for schema.org `image`.
export const OG_IMAGE = `${SITE_URL}/opengraph-image`;

// priceRange is display prose ("Rp 150.000 - Rp 2.000.000"), not a number, so offers
// carries only the ticket URL. Never emit offers as [] — an empty array fails Google's
// required-field check exactly as hard as omitting the key. Events without a ticketUrl
// fall back to the event page itself so `offers` is always present.
export function eventJsonLd(event: SportEvent) {
  return {
    '@type': 'SportsEvent',
    '@id': `${SITE_URL}/events/${event.slug}#event`,
    name: event.title,
    description: event.description,
    startDate: event.startDate,
    endDate: event.endDate,
    eventStatus:
      event.status === 'tentative'
        ? 'https://schema.org/EventPostponed'
        : 'https://schema.org/EventScheduled',
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    sport: SPORT_LABELS[event.sport],
    url: `${SITE_URL}/events/${event.slug}`,
    image: [OG_IMAGE],
    location: {
      '@type': 'Place',
      name: event.venue,
      address: {
        '@type': 'PostalAddress',
        addressLocality: event.city,
        addressCountry: event.country,
      },
    },
    // Google requires `performer`. `athletes` is free prose when present;
    // otherwise the organizing body is the closest accurate performer.
    performer: {
      '@type': 'PerformingGroup',
      name: event.athletes || event.organizer || event.title,
    },
    organizer: event.organizer
      ? { '@type': 'Organization', name: event.organizer, url: event.websiteUrl || SITE_URL }
      : { '@type': 'Organization', name: 'Sport Event Indonesia', url: SITE_URL },
    offers: {
      '@type': 'Offer',
      url: event.ticketUrl || `${SITE_URL}/events/${event.slug}`,
      availability:
        event.status === 'completed'
          ? 'https://schema.org/SoldOut'
          : 'https://schema.org/InStock',
      ...(event.priceRange && { description: event.priceRange }),
    },
  };
}
